### ISSUE TITLE
Changing minimap size and position

### ISSUE THREAD

**Issue by Huioolo** [drweissbrot/cs-hud#191]
How do I change the minimap size and position?

**Comment by drweissbrot** [comment]
see #127 for resizing

changing the position should work similarly, you could try e.g.
```css
.radar {
    width: 25%;
    tranform: translate(10px, 20px);
}
```
